uuid = "1802598046"
nome = "Maria"
sexo = "F"
local-nascimento = "Sao Paulo - SP"
data-nascimento = "1970-04-10"
[[parceiros]]
uuid = "659748578"
nome = "Joao"
sexo = "M"
local-nascimento = "Rio de Janeiro - RJ"
data-nascimento = "1971-08-20"
[[parceiros.filhos]]
uuid = "483422889"
nome = "Joana"
sexo = "F"
local-nascimento = "Belo Horizonte - BH"
data-nascimento = "1992-08-03"
[[parceiros.filhos]]
uuid = "2088051243"
nome = "Mariana"
sexo = "F"
local-nascimento = "Belo Horizonte - BH"
data-nascimento = "1994-01-08"
[[parceiros.filhos.parceiros]]
uuid = "1277181601"
nome = "Otavio"
sexo = "M"
local-nascimento = "Belo Horizonte - BH"
data-nascimento = "1990-08-23"
[[parceiros]]
uuid = "41903949"
nome = "Jose"
sexo = "M"
local-nascimento = "Cuiaba - MT"
data-nascimento = "1971-03-02"
[[parceiros.filhos]]
uuid = "488970385"
nome = "Mario"
sexo = "M"
local-nascimento = "Belo Horizonte - BH"
data-nascimento = "1995-02-01"
[[parceiros.filhos.parceiros]]
uuid = "1209271652"
nome = "Ana"
sexo = "F"
local-nascimento = "Belo Horizonte - BH"
data-nascimento = "1990-01-30"
[[parceiros.filhos.parceiros.filhos]]
uuid = "93122545"
nome = "Tatiana"
sexo = "F"
local-nascimento = "Belo Horizonte - BH"
data-nascimento = "2018-08-23"
