uuid = "468121027"
nome = "Maria"
sexo = "F"
local-nascimento = "Sao Paulo - SP"
data-nascimento = "1970-04-10"
[[parceiros]]
uuid = "1804094807"
nome = "Joao"
sexo = "M"
local-nascimento = "Rio de Janeiro - RJ"
data-nascimento = "1971-08-20"
[[parceiros.filhos]]
uuid = "2001049719"
nome = "Joana"
sexo = "F"
local-nascimento = "Belo Horizonte - BH"
data-nascimento = "1992-08-03"
[[parceiros.filhos]]
uuid = "1528902577"
nome = "Mariana"
sexo = "F"
local-nascimento = "Belo Horizonte - BH"
data-nascimento = "1994-01-08"
[[parceiros.filhos.parceiros]]
uuid = "1927950199"
nome = "Otavio"
sexo = "M"
local-nascimento = "Belo Horizonte - BH"
data-nascimento = "1990-08-23"
[[parceiros]]
uuid = "868693306"
nome = "Jose"
sexo = "M"
local-nascimento = "Cuiaba - MT"
data-nascimento = "1971-03-02"
[[parceiros.filhos]]
uuid = "1746572565"
nome = "Mario"
sexo = "M"
local-nascimento = "Belo Horizonte - BH"
data-nascimento = "1995-02-01"
[[parceiros.filhos.parceiros]]
uuid = "989110044"
nome = "Ana"
sexo = "F"
local-nascimento = "Belo Horizonte - BH"
data-nascimento = "1990-01-30"
[[parceiros.filhos.parceiros.filhos]]
uuid = "424058530"
nome = "Tatiana"
sexo = "F"
local-nascimento = "Belo Horizonte - BH"
data-nascimento = "2018-08-23"
